### PR TITLE
126 soap service not exported

### LINKED ISSUE #126: `BundleLoadException: Multiple l7:ResourceSet elements found` exporting SOAP service
**Describe the bug**
Create a soap service using policy manager (You can use any wsdl)

**To Reproduce**
1. Create a soap service using policy manager (You can use any wsdl)
2. Export a solution that contains this service
3. See the following error:
    * `BundleLoadException: Multiple l7:ResourceSet elements found` 

**Expected behavior**
Should have successfully exported

### PR DESCRIPTION
**Pull request by amoghsa**
Fixes #126 

## Proposed Changes
* Added a new method to extract information about service.
* Removed duplicate method from DocumentUtils

### CODE REVIEW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java [hunk 1]
```diff
@@ -86,4 +115,52 @@ public void load(Bundle bundle, Element element) {
...
+     *      <l7:Property key="internal">
+     *          <l7:BooleanValue>false</l7:BooleanValue>
+     *      </l7:Property>
+     *      <l7:Property key="policyRevision">
+     *          <l7:LongValue>1</l7:LongValue>
+     *      </l7:Property>
+     *      <l7:Property key="soap">
+     *          <l7:BooleanValue>true</l7:BooleanValue>
+     *      </l7:Property>
+     *      <l7:Property key="soapVersion">
```
[the remark this answers is not in the document]
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: I had a chat with @kazvictor. I am storing soapVersion for now. Please check latest.

**Comment by amoghsa** [comment]
Team, I have added 2 private methods in test, please check and let me know which way do you prefer most? Common method for 2 tests or 2 different methods for 2 test? There are pros and cons. Common method reduces code and second one keeps them separate, and hopefully we can run them in parallel without any issues inn future.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java [hunk 2]
```diff
@@ -6,29 +6,31 @@
...
 @Singleton
 public class ServiceLoader implements BundleEntityLoader {
 
+    static final String KEY_VALUE_SOAP = "soap";
+    static final String KEY_VALUE_SOAP_VERSION = "soapVersion";
+    static final String TAG_VALUE_POLICY = "policy";
+    static final String TAG_VALUE_WSDL = "wsdl";
+
     @Override
     public void load(Bundle bundle, Element element) {
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: Code Smell Code Smell: Refactor this method to reduce its Cognitive Complexity from 24 to the 15 allowed. ([squid:S3776](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS3776))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=130&issues=AWcUvrYBkEeD8QRkNhVh&open=AWcUvrYBkEeD8QRkNhVh)

[ISSUE_KEY]: AWcUvrYBkEeD8QRkNhVh

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java [hunk 3]
```diff
@@ -6,29 +6,31 @@
...
 
 import static com.ca.apim.gateway.cagatewayconfig.util.gateway.BundleElementNames.*;
-import static com.ca.apim.gateway.cagatewayconfig.util.xml.DocumentUtils.getSingleChildElement;
-import static com.ca.apim.gateway.cagatewayconfig.util.xml.DocumentUtils.nodeList;
+import static com.ca.apim.gateway.cagatewayconfig.util.xml.DocumentUtils.*;
 
 @Singleton
 public class ServiceLoader implements BundleEntityLoader {
 
+    private static final String KEY_VALUE_SOAP = "soap";
```
[the remark this answers is not in the document]
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: done.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java (hunk 2 above)
Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: Try to split this into 2 or 3 methods so we workaround this warning.

File: config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoaderTest.java [hunk 4]
```diff
@@ -58,6 +58,125 @@ void load() {
...
+        assertEquals("folder", service.getParentFolder().getId());
+        assertEquals("wsdl file", service.getWsdl().getWsdlXml());
+        assertEquals("1.1", service.getWsdl().getSoapVersion());
+        Map<String, Object> expected = new HashMap<>();
+        expected.put("prop", "value");
+        expected.put("ENV.prop", null);
+        assertPropertiesContent(expected, service.getProperties());
+    }
+
+    private static Element createCommonXml(Document document, boolean isSoap) {
```
Comment (joao-borges) [inline config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoaderTest.java]: It's good the methods here, I just think you could do some refactoring adding parameters to the method so you end with only one method building the xml and less duplicated stuff.

Comment (amoghsa) [reply config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoaderTest.java]: I did not understand you.. This is common method for both tests.

Comment (joao-borges) [reply config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoaderTest.java]: Sorry I got confused by the github view, I pulled your branch and I see you are using the same method for both tests, but there are unused methods in the class so remove them and it's fine =)

**Comment by joao-borges** [comment]
@amoghsa, I tested your branch here and I ended up with the wsdl saved to the yaml file.
Is this correct?

**Comment by amoghsa** [comment]
That's right @joao-borges , it saves wsdl file inn yaml file, as per suggestion by @kazvictor ..

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java [hunk 5]
```diff
@@ -39,19 +41,46 @@ public void load(Bundle bundle, Element element) {
         Element nameElement = getSingleChildElement(serviceDetails, NAME);
         final String name = EncodeDecodeUtils.encodePath(nameElement.getTextContent());
 
+        Element propertiesElement = getSingleChildElement(serviceDetails, PROPERTIES);
```
[the remark this answers is not in the document]
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: done.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: done.

**Comment by kazvictor** [comment]
> That's right @joao-borges , it saves wsdl file inn yaml file, as per suggestion by @kazvictor ..

Ya, I understand it's not ideal but it's ok for now

**Comment by kazvictor** [comment]
The `com.ca.apim.gateway.cagatewayconfig.bundle.builder.ServiceEntityBuilder` should also be updated in this PR so that the wsdl is added back to the service entity when the bundle is built

**Comment by amoghsa** [comment]
@joao-borges and @kazvictor, I am checking on ServiceEntityBuilder now. Can someone please review ServiceLoader and tests? Unfortunately I disabled one of the sonar lint warnings on my intellij, since then I am not able to see cognitive factor on load() method, I tried removing sonarlint folder reinstalling plugin, but nothing worked so far. Can you please check if that has been fixed?

**Comment by yves-chan** [comment]
@amoghsa I pulled your latest branch and I don't see the sonar warning for the load method in ServiceLoader. I will take a look at the tests too

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java [hunk 6]
```diff
@@ -60,29 +60,7 @@ public void load(Bundle bundle, Element element) {
...
-                    } else {
-                        WSDL wsdlBean = new WSDL();
-                        wsdlBean.setUrl(rootUrlForWsdl);
-                        wsdlBean.setWsdlXml(wsdl);
-                        wsdlBean.setSoapVersion(soapVersion);
-                        serviceEntity.setWsdl(wsdlBean);
-                    }
-                }
-            }
+            extraxtResourceSets(soapVersion, resources, serviceEntity);
```
[the remark this answers is not in the document]
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/loader/ServiceLoader.java]: good catch.. thanks..

**Comment by amoghsa** [comment]
@yves-chan thanks..

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java [hunk 7]
```diff
@@ -67,24 +71,38 @@ private Entity buildServiceEntity(Bundle bundle, String servicePath, Service ser
...
-                            .stream()
-                            .collect(Collectors
-                                    .toMap(p -> "property." + p.getKey(), p -> p.getKey().startsWith(PREFIX_ENV) ? "SERVICE_PROPERTY_" + p.getKey() : p.getValue())),
+            Map<String, Object> properties = service.getProperties()
+                    .entrySet()
+                    .stream()
+                    .collect(Collectors
+                            .toMap(p -> "property." + p.getKey(), p -> p.getKey().startsWith(PREFIX_ENV) ? "SERVICE_PROPERTY_" + p.getKey() : p.getValue()));
+
+            if(isSoapService) {
```
Comment (joao-borges) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java]: I think your properties have to stay out of this condition service.getProperties != null
If you have a soap service, that does not have any other properties, you will end up with a bundle with the WSDL and everything, but without the isSoap = true and the soapVersion because the getProperties was null.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/WSDL.java [hunk 8]
```diff
@@ -0,0 +1,35 @@
+package com.ca.apim.gateway.cagatewayconfig.beans;
+
+import com.fasterxml.jackson.annotation.JsonIgnore;
+
+public class WSDL {
+
+    @JsonIgnore
+    private String rootUrl;
```
Comment (yves-chan) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/WSDL.java]: I think we should not ignore the rootUrl, if it is the link to Wsdl. When building, getRootUrl will return nulls.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java [hunk 9]
```diff
@@ -67,24 +71,38 @@ private Entity buildServiceEntity(Bundle bundle, String servicePath, Service ser
...
-        Element resourceElement = createElementWithAttribute(document, RESOURCE, "type", "policy");
-        resourceElement.setTextContent(documentFileUtils.elementToString(policy.getPolicyDocument()));
+        Element policyResourceSetElement = createElementWithAttribute(document, RESOURCE_SET, ATTRIBUTE_TAG, TAG_VALUE_POLICY);
+        Element policyResourceElement = createElementWithAttribute(document, RESOURCE, ATTRIBUTE_TYPE, TAG_VALUE_POLICY);
+        policyResourceElement.setTextContent(documentFileUtils.elementToString(policy.getPolicyDocument()));
+        policyResourceSetElement.appendChild(policyResourceElement);
+        resourcesElement.appendChild(policyResourceSetElement);
+
+        if(isSoapService) {
+            Element wsdlResourceSetElement = createElementWithAttributes(document, RESOURCE_SET, ImmutableMap.of(ATTRIBUTE_TAG, TAG_VALUE_WSDL, ATTRIBUTE_ROOT_URL, wsdlBean.getRootUrl()));
```
Comment (yves-chan) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java]: wsdlBean.getRootUrl() will return null if the jsonIgnore is set for the rootUrl property in a situation that is export and then build

**Comment by yves-chan** [comment]
Can we also add some tests to [config ServiceLoaderTest](https://github.com/ca-api-gateway/gateway-developer-plugin/blob/master/config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/config/loader/ServiceLoaderTest.java) and [ServiceEntityBuilderTest](https://github.com/ca-api-gateway/gateway-developer-plugin/blob/master/config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilderTest.java)?

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java (hunk 7 above)
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java]: yup.. you are right.. I will segregate this.. thanks

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/WSDL.java (hunk 8 above)
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/WSDL.java]: yeah you are right.. I was having problem while running build already..

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java (hunk 9 above)
Comment (amoghsa) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java]: that's was I was having problem at.. :)

**Comment by amoghsa** [comment]
Give me until evening, I am checking in few more changes and unit tests..

**Comment by amoghsa** [comment]
@yves-chan, @kazvictor changes are in.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java [hunk 10]
```diff
@@ -66,25 +71,47 @@ private Entity buildServiceEntity(Bundle bundle, String servicePath, Service ser
         serviceDetailElement.appendChild(createElementWithTextContent(document, ENABLED, Boolean.TRUE.toString()));
         serviceDetailElement.appendChild(buildServiceMappings(service, document));
```
Comment (kazvictor) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/ServiceEntityBuilder.java]: in `buildServiceMappings` need to add:
```java
        if(service.getUrl() != null) {
            httpMappingElement.appendChild(createElementWithTextContent(document, URL_PATTERN, service.getUrl()));
        }
```
