### PR TITLE
Bugfix/110 Export failure when non-existent folder path is specified

### LINKED ISSUE #110: Export should fail when folderPath does not exist
**Describe the bug**
Export build should fail when export folder path does not exist

**To Reproduce**
1.  In gradle settings, set GatewayConnection.folderPath to an invalid folder (asdf)
2. Run command`gradle export`
3. Build passes

**Expected behavior**
Build should fail

### PR DESCRIPTION
**Pull request by J-Lou**
Fixes #110 

## Proposed Changes
* Compare specified folder in Gateway connection folder path with the filtered folders found in bundle

### CODE REVIEW

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java [hunk 1]
```diff
@@ -53,4 +54,20 @@ public Bundle filter(String folderPath, FilterConfiguration filterConfiguration,
...
+        // Verifies if node folder is found or if Root Node is found only if the base directory is specified
+        for (Folder folder : bundle.getFolders().values()) {
+            if (folderPath.endsWith(folder.getName()) || 
+                (folderPath.equals("/") && folder.getName().equals("Root Node"))) {
+                isValidImport = true;
+            }
+        }
+
+        if (!isValidImport) {
+            throw new RuntimeException("Unable to find specified folder \"" + folderPath + "\" in the Gateway connection folder path");
```
Comment (J-Lou) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java]: I feel like I have the wrong exception here.

Comment (yves-chan) [reply gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java]: Could use "EntityFilterException" here since you've put this method in the BundleFilter

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 2]
```diff
@@ -49,6 +50,8 @@ void explodeBundle(String folderPath, FilterConfiguration filterConfiguration, F
         BundleFilter bundleFilter = ExportPluginModule.getInjector().getInstance(BundleFilter.class);
         Bundle filteredBundle = bundleFilter.filter(folderPath, filterConfiguration, bundle);
 
+        bundleFilter.validateImportedFolder(folderPath, filteredBundle);
```
Comment (joao-borges) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: is this the right place for doing this?
I mean, some lines above you have the full bundle loaded with no filtering, so you could check before if the folder path is valid and stop there if not, then you avoid extra processing that will be useless.

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java [hunk 3]
```diff
@@ -53,4 +54,20 @@ public Bundle filter(String folderPath, FilterConfiguration filterConfiguration,
         return filteredBundle;
     }
 
+    public void validateImportedFolder(String folderPath, Bundle bundle) {
+        Boolean isValidImport = false;
+
+        // Verifies if node folder is found or if Root Node is found only if the base directory is specified
+        for (Folder folder : bundle.getFolders().values()) {
+            if (folderPath.endsWith(folder.getName()) || 
+                (folderPath.equals("/") && folder.getName().equals("Root Node"))) {
```
[the remark this answers is not in the document]
Comment (joao-borges) [reply gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java]: Yves is correct, you have to navigate the folders as a tree not as a list.
split the path and search from leaf path nodes and go up to check if the full path match. Folder objects have reference to their parents so this way should be easy to check.

Also the root folder attributes have constants into Folder class, please use :)

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java (hunk 1 above)
Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java]: Code Smell Code Smell: Define and throw a dedicated exception instead of using a generic one. ([squid:S00112](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS00112))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobj9kEeD8QRklwaV&open=AWcZobj9kEeD8QRklwaV)

[ISSUE_KEY]: AWcZobj9kEeD8QRklwaV

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java [hunk 4]
```diff
@@ -202,4 +202,34 @@ public void setFolderTree(FolderTree folderTree) {
...
+        if (folderList.length > 0) {
+            String leafFolderName = folderList[folderList.length - 1];
+            Folder leafFolder = new Folder();
+            for (Folder folder : bundle.getFolders().values()) {
+                if (folder.getName().equals(leafFolderName)) {
+                    leafFolder = folder;
+                }
+            }
+
+            String leafFolderPath = "/" + leafFolder.getPath();
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Remove this hard-coded path-delimiter. ([squid:S1075](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS1075))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkXkEeD8QRklwaY&open=AWcZobkXkEeD8QRklwaY)

[ISSUE_KEY]: AWcZobkXkEeD8QRklwaY

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 5]
```diff
@@ -7,6 +7,7 @@
 package com.ca.apim.gateway.cagatewayexport.tasks.explode;
 
 import com.ca.apim.gateway.cagatewayconfig.beans.Bundle;
+import com.ca.apim.gateway.cagatewayconfig.beans.Folder;
```
Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Code Smell Code Smell: Remove this unused import 'com.ca.apim.gateway.cagatewayconfig.beans.Folder'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkIkEeD8QRklwaW&open=AWcZobkIkEeD8QRklwaW)

[ISSUE_KEY]: AWcZobkIkEeD8QRklwaW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java [hunk 6]
```diff
@@ -202,4 +202,34 @@ public void setFolderTree(FolderTree folderTree) {
...
+            if (folderPath.equals(leafFolderPath)) {
+                isValidImport = true;
+            }
+        }
+
+        if (!isValidImport) {
+            throw new RuntimeException("Unable to find specified folder \"" + folderPath + "\" in the Gateway connection folder path");
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Define and throw a dedicated exception instead of using a generic one. ([squid:S00112](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS00112))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkXkEeD8QRklwaX&open=AWcZobkXkEeD8QRklwaX)

[ISSUE_KEY]: AWcZobkXkEeD8QRklwaX

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java (hunk 5 above)
Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Code Smell Code Smell: Remove this unused import 'com.ca.apim.gateway.cagatewayconfig.beans.Folder'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkIkEeD8QRklwaW&open=AWcZobkIkEeD8QRklwaW)

[ISSUE_KEY]: AWcZobkIkEeD8QRklwaW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java (hunk 4 above)
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Remove this hard-coded path-delimiter. ([squid:S1075](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS1075))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkXkEeD8QRklwaY&open=AWcZobkXkEeD8QRklwaY)

[ISSUE_KEY]: AWcZobkXkEeD8QRklwaY

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java (hunk 6 above)
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Define and throw a dedicated exception instead of using a generic one. ([squid:S00112](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS00112))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkXkEeD8QRklwaX&open=AWcZobkXkEeD8QRklwaX)

[ISSUE_KEY]: AWcZobkXkEeD8QRklwaX

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java [hunk 7]
```diff
@@ -202,4 +202,34 @@ public void setFolderTree(FolderTree folderTree) {
...
+            isValidImport = true;
+        }
+        
+        // Compares the folder tree path structure with specified Gateway connection folder path
+        String[] folderList = folderPath.split("/");
+        if (folderList.length > 0) {
+            String leafFolderName = folderList[folderList.length - 1];
+            Folder leafFolder = new Folder();
+            for (Folder folder : bundle.getFolders().values()) {
+                if (folder.getName().equals(leafFolderName)) {
```
[the remark this answers is not in the document]
Comment (kazvictor) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: you should be able to just do: `bundle.getFolders().containsValue(folderPath)`

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java (hunk 5 above)
Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Code Smell Code Smell: Remove this unused import 'com.ca.apim.gateway.cagatewayconfig.beans.Folder'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkIkEeD8QRklwaW&open=AWcZobkIkEeD8QRklwaW)

[ISSUE_KEY]: AWcZobkIkEeD8QRklwaW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java [hunk 8]
```diff
@@ -202,4 +202,26 @@ public void setFolderTree(FolderTree folderTree) {
...
+            isValidImport = true;
+        }
+        
+        long matchingFolderPaths = getFolders().values()
+            .stream()
+            .filter(folder -> ("/" + folder.getPath()).equals(folderPath))
+            .count();
+        
+        if (matchingFolderPaths > 0) {
+            isValidImport = true;
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Define and throw a dedicated exception instead of using a generic one. ([squid:S00112](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS00112))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcZobkXkEeD8QRklwaX&open=AWcZobkXkEeD8QRklwaX)

[ISSUE_KEY]: AWcZobkXkEeD8QRklwaX

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java [hunk 9]
```diff
@@ -202,4 +202,26 @@ public void setFolderTree(FolderTree folderTree) {
...
         this.dependencyMap = dependencyMap;
     }
+
+    public void verifyExistingFolderPath(String folderPath) {
+        boolean isValidImport = false;
+
+        // True because there isn't a specific directory.
+        if (folderPath.equals("/")) {
+            isValidImport = true;
+        }
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: Code Smell Code Smell: Remove this hard-coded path-delimiter. ([squid:S1075](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS1075))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWct0dyzKqTTJP1B-7zk&open=AWct0dyzKqTTJP1B-7zk)

[ISSUE_KEY]: AWct0dyzKqTTJP1B-7zk

Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Bundle.java]: @J-Lou add a warning ignore for this squid because this has to be hard-coded.

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 10]
```diff
@@ -45,10 +46,12 @@ void explodeBundle(String folderPath, FilterConfiguration filterConfiguration, F
         final BundleBuilder bundleBuilder = ExportPluginModule.getInjector().getInstance(BundleBuilder.class);
         Bundle bundle = bundleBuilder.buildBundle(bundleDocument.getDocumentElement());
 
+        bundle.verifyExistingFolderPath(folderPath);
```
Comment (joao-borges) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: add some comment here what this is doing

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 11]
```diff
@@ -45,10 +46,12 @@ void explodeBundle(String folderPath, FilterConfiguration filterConfiguration, F
...
+
         //filter out unwanted entities
         BundleFilter bundleFilter = ExportPluginModule.getInjector().getInstance(BundleFilter.class);
         Bundle filteredBundle = bundleFilter.filter(folderPath, filterConfiguration, bundle);
-
+
```
Comment (joao-borges) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: there is some unnecessary extra space here

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 12]
```diff
@@ -37,6 +38,14 @@
         this.entityLinkerRegistry = entityLinkerRegistry;
     }
 
+    void verifyExistingFolderPath(Bundle bundle, String folderPath) {
+        if (folderPath.equals("/")) {
+            return;
```
Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Code Smell Code Smell: Remove this redundant jump. ([squid:S3626](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS3626))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcucRmYKqTTJP1BKO56&open=AWcucRmYKqTTJP1BKO56)

[ISSUE_KEY]: AWcucRmYKqTTJP1BKO56

Comment (apigatewayopensource) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Code Smell Code Smell: Remove this redundant jump. ([squid:S3626](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS3626))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=131&issues=AWcucRmYKqTTJP1BKO56&open=AWcucRmYKqTTJP1BKO56)

[ISSUE_KEY]: AWcucRmYKqTTJP1BKO56

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 13]
```diff
@@ -45,10 +56,14 @@ void explodeBundle(String folderPath, FilterConfiguration filterConfiguration, F
         final BundleBuilder bundleBuilder = ExportPluginModule.getInjector().getInstance(BundleBuilder.class);
         Bundle bundle = bundleBuilder.buildBundle(bundleDocument.getDocumentElement());
 
+        //checks if bundle has specified folderpath
+        if (!bundleContainsFolderPath(bundle, folderPath)) {
+            throw new BundleLoadException("Unable to find " + folderPath + " in the Gateway from the specified Gateway connection folder path");
```
Comment (joao-borges) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: simple improvement in the message here, I think it's better something like this:
`Specified folder + folderPath + does not exist in the target gateway.`

File: gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java [hunk 14]
```diff
@@ -37,6 +38,14 @@
         this.entityLinkerRegistry = entityLinkerRegistry;
     }
 
+    @SuppressWarnings("squid:S1075")
+    boolean bundleContainsFolderPath(Bundle bundle, String folderPath) {
```
Comment (yves-chan) [inline gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: Can be package private here, also double check if we still need to suppress the warning

Comment (J-Lou) [reply gateway-export-plugin/src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java]: I believe by default, with no modifier it's package private.

**Comment by joao-borges** [comment]
@J-Lou, just make the small fix in the error message and we are good to merge.
