### PR TITLE
Environment entities directly linked to services fail the startup

### LINKED ISSUE #165: Environment entities directly linked to services fail the startup
Listen Ports or JMS Inbound Destinations that have directly link to services in order to route messages will prevent the container to start.

At the time of the environment bundle building, services are not available yet (because are into deployment bundles) and cannot be referenced.
Deployment bundle contents should be exposed to environment bundle building to allow proper referencing.

### PR DESCRIPTION
**Pull request by J-Lou**
Fixes #165 / [DE405300](https://rally1.rallydev.com/#/56296273706d/detail/defect/286951310920)

## Proposed Changes
*
*
*

### CODE REVIEW

File: config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilderTest.java [hunk 1]
```diff
@@ -325,7 +325,6 @@ private static void verifyInbound(Entity entity) {
         
         assertEquals("AUTOMATIC", jmsDestinationDetailProps.remove(INBOUND_ACKNOWLEDGEMENT_TYPE));
         assertEquals("AUTOMATIC", jmsDestinationDetailProps.remove(REPLY_TYPE));
-        assertEquals("true", contextPropertiesTemplateProps.remove(IS_HARDWIRED_SERVICE));
         assertEquals("my-service-id", contextPropertiesTemplateProps.remove(HARDWIRED_SERVICE_ID));
```
Comment (kevpak) [inline config-builder/src/test/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilderTest.java]: Add  back this `assertEquals` statement.

If Inbound JMS destination is configured to be associated to a specific service, then `IS_HARDWIRED_SERVICE` must be set to `true`. Otherwise, it won't resolve to that specific service.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java [hunk 2]
```diff
@@ -222,15 +224,21 @@ private void buildInboundDestination (
...
+
+            if (service == null) {
+                if (getDeploymentBundle() == null) {
                     throw new EntityBuilderException("Could not find associated Service for inbound JMS Destination: " + name + ". Service Path: " + serviceRef);
+                } else {
+                    service = getDeploymentBundle().getServices().get(serviceRef.substring(serviceRef.lastIndexOf('/') + 1));
                 }
+            }
+
+            if (service == null) {
```
Comment (kevpak) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java]: If `serviceRef` is not null, but the corresponding `service` is not found in the bundle, then this is an error.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java [hunk 3]
```diff
@@ -222,15 +224,21 @@ private void buildInboundDestination (
...
             String serviceRef = serviceResolutionSettings.getServiceRef();
-            if (serviceRef != null) {
-                Service service = bundle.getServices().get(serviceRef);
-                if (service == null) {
-                    throw new EntityBuilderException("Could not find associated Service for inbound JMS Destination: " + name + ". Service Path: " + serviceRef);
-                }
+            Service service = bundle.getServices().get(serviceRef);
+
+            if (service == null) {
+                service = getDeploymentBundle().getServices().get(serviceRef.substring(serviceRef.lastIndexOf('/') + 1));
```
[the remark this answers is not in the document]
Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/bundle/builder/JmsDestinationEntityBuilder.java]: I think we have because the services are referenced by path if I am not mistaken.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java [hunk 4]
```diff
@@ -24,8 +30,23 @@
...
+        templatizedBundlesFolderPath = folderPath;
+    }
+
+    public static Bundle getDeploymentBundle() {
+        if (templatizedBundlesFolderPath == null) {
+            throw new BundleLoadException("Invalid deployment bundle path : " + templatizedBundlesFolderPath);
+        }
+        EntityBundleLoader loader = ConfigBuilderModule.getInjector().getInstance(EntityBundleLoader.class);
+        List<File> deploymentBundleFiles = collectFiles(templatizedBundlesFolderPath, BUNDLE_EXTENSION);
+        return loader.load(deploymentBundleFiles);
```
Comment (joao-borges) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java]: You may want to cache this bundle instance so you don't have to read every time someone call this method.
Actually is used only once, but it will be more used.

Comment (J-Lou) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java]: I think this may be out of scope for now. It should be added to rally as an improvement.

Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java]: You are adding an extra step of loading bundles for every listen port, and you are reloading files from disk every time.
I know this does not happen now but lets imagine someone have 10 listen ports specified and and 10 deployment bundles, none of the listen ports pointing to any service, and in this case you will be reading 10 times the same 10 files for nothing, which goes to 100 I/O operations.
I think it won't be that much work to cache the bundle instance and you avoid 99 IO operations in this case.

if the code isn't that easy ok, but it's probably something we would have to fix soon.

Comment (J-Lou) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java]: Ah, I understand. I'll look into it further.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCache.java [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+
+import com.ca.apim.gateway.cagatewayconfig.beans.Bundle;
+
+import javax.inject.Inject;
+import javax.inject.Singleton;
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+
+@Singleton
+public class EnvironmentBundleCache {
```
Comment (joao-borges) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleCache.java]: I think you could name this only as BundleCache

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java [hunk 6]
```diff
@@ -42,9 +42,18 @@ public static Bundle getDeploymentBundle() {
...
-        return loader.load(deploymentBundleFiles);
+
+        EnvironmentBundleCache cache = ConfigBuilderModule.getInjector().getInstance(EnvironmentBundleCache.class);
+
+        if (cache.contains(templatizedBundlesFolderPath)) {
+            return cache.getBundle(templatizedBundlesFolderPath);
+        } else {
+            EntityBundleLoader loader = ConfigBuilderModule.getInjector().getInstance(EntityBundleLoader.class);
+            List<File> deploymentBundleFiles = collectFiles(templatizedBundlesFolderPath, BUNDLE_EXTENSION);
+            ConfigBuilderModule.getInjector().getInstance(EnvironmentBundleCache.class).putBundle(templatizedBundlesFolderPath, loader.load(deploymentBundleFiles));
```
Comment (joao-borges) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/environment/EnvironmentBundleUtils.java]: use the cache object, dont need to get it again from the injector
