### PR TITLE
Referencing Authenticate by Id Prov by name instead of ID

### LINKED ISSUE #113: Authenticate Against Identity Provider assertion used identity provider id not name
**Describe the bug**
The Authenticate against Identity Provider Assertion uses the identity provider ID. This makes it not usable with the gateway-developer-plugins since the identity provider ID is always autogenerated. We should use the identity provider name instead. 

Original assertion xml:
```xml
        <L7p:Authentication>
            <L7p:IdentityProviderOid goidValue="1acc763f4c7f5d8088a3761d8068198e"/>
        </L7p:Authentication>
```
Suggested updated xml:
```xml
        <L7p:Authentication>
            <L7p:IdentityProviderName stringValue="My-IDP"/>
        </L7p:Authentication>
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create policy with Authenticate against Identity Provider Assertion
2. export solution with that policy `./gradlew export`
3. View the policy xml

**Expected behaviour**
Identity providers should be referred to by name in policy xml.

**Additional context**
There may be additional assertions that refer to identity providers by ID. Take a quick looks at making those use names as well.

### PR DESCRIPTION
**Pull request by yves-chan**
Fixes #113

## Proposed Changes
```xml
<L7p:Authentication>
    <L7p:IdentityProviderName stringValue="My-IDP"/>
</L7p:Authentication>
```
* translates the old L7p:IdentityProviderOid tag to the format above during export
* translates to the format above from the old L7p:IdentityProviderOid tag during build
* Added unit tests

Side note: other assertions that reference Identity providers are Authenticate Against Group and Authenticate Against User assertions. But those also require User and Group entity support, I've added those tickets to the backlog to be prioritized and finished when needed

### CODE REVIEW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java [hunk 1]
```diff
@@ -178,6 +181,57 @@ static void prepareEncapsulatedAssertion(Policy policy, Bundle bundle, Document
...
+
+        authenticationAssertionElement.removeChild(nameElement);
+    }
+
+    private static String findIdentityProviderId(Policy policy, Bundle bundle, String name) {
+        LOGGER.log(Level.FINE, "Looking for referenced identity provider: {0}", name);
+        if (name.equals(INTERNAL_IDP_NAME)) {
+            return INTERNAL_IDP_ID;
+        }
+        final AtomicReference<IdentityProvider> referenceIdentityProvider = new AtomicReference<>(bundle.getIdentityProviders().get(name));
```
Comment (kazvictor) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java]: This will need to be handled differently because we won't know the ID provider name at deployment bundle build time. We will only know the ID at Environment bundle creation time. It should work somewhat similarly to the way the ENV. context variables are set. In the [PolicyEntityBuilder we put a reference](https://github.com/ca-api-gateway/gateway-developer-plugin/blob/9136ede3a6c02244fb1eeb93f8d7d5951cfa6af2/config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java#L124). And in the [BundleDetemplatizer we provide the value](https://github.com/ca-api-gateway/gateway-developer-plugin/blob/9136ede3a6c02244fb1eeb93f8d7d5951cfa6af2/environment-creator-application/src/main/java/com/ca/apim/gateway/cagatewayconfig/BundleDetemplatizer.java#L28).

Comment (yves-chan) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/tasks/zip/builder/PolicyEntityBuilder.java]: I will look into referencing and using the bundleDetemplatizer way, thanks for the quick links

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/IdentityProvider.java [hunk 2]
```diff
@@ -62,6 +66,14 @@ private IdentityProvider(Builder builder) {
     })
     private IdentityProviderDetail identityProviderDetail;
 
+    public String getId() {
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/IdentityProvider.java]: Code Smell Code Smell: Add the "@Override" annotation above this method signature ([squid:S1161](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS1161))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=121&issues=AWbqThqoTJjFgJLTIz5X&open=AWbqThqoTJjFgJLTIz5X)

[ISSUE_KEY]: AWbqThqoTJjFgJLTIz5X

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/IdentityProvider.java [hunk 3]
```diff
@@ -62,6 +66,14 @@ private IdentityProvider(Builder builder) {
...
+        return id;
+    }
+
+    public void setId(String id) {
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/IdentityProvider.java]: Code Smell Code Smell: Add the "@Override" annotation above this method signature ([squid:S1161](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AS1161))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=121&issues=AWbqThqoTJjFgJLTIz5Y&open=AWbqThqoTJjFgJLTIz5Y)

[ISSUE_KEY]: AWbqThqoTJjFgJLTIz5Y
