### PR TITLE
Windows fixes

### LINKED ISSUE #119: Test the plugins on a windows computer
Looks like there may be issues locating policies when attempting to build Gateway solutions on windows machines:

```
C:\Users\username\Documents\CA Gateway Developer Plugin\gateway-developer-example>gradle build
> Task :consumer-solutions:build-bundle FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':consumer-solutions:build-bundle'.
> Could not find referenced policy include with path: common/auth/basic-auth.xml
```

### PR DESCRIPTION
**Pull request by joao-borges**
Fixes #119 

## Proposed Changes
* Paths using Windows file separators are converted to Unix file separators after loading entities (affects policies, services and folders)
* Ensure folders are created properly in any OS
* All file streams must be properly closed in windows, otherwise temporary files and cleaning tasks fail to execute due to `file is currently in use by other program` error
* Creating `.gitattributes` file to force `\n` as line separator instead of `\n\r`

### CODE REVIEW

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Policy.java [hunk 1]
```diff
@@ -7,11 +7,16 @@
 package com.ca.apim.gateway.cagatewayconfig.beans;
 
 import com.ca.apim.gateway.cagatewayconfig.config.loader.ConfigLoadException;
+import com.ca.apim.gateway.cagatewayconfig.util.IdGenerator;
+import com.ca.apim.gateway.cagatewayconfig.util.file.DocumentFileUtils;
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Policy.java]: Code Smell Code Smell: Remove this unused import 'com.ca.apim.gateway.cagatewayconfig.util.file.DocumentFileUtils'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=135&issues=AWcuGG63kEeD8QRk-1yQ&open=AWcuGG63kEeD8QRk-1yQ)

[ISSUE_KEY]: AWcuGG63kEeD8QRk-1yQ

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Policy.java [hunk 2]
```diff
@@ -7,11 +7,16 @@
...
 import com.fasterxml.jackson.annotation.JsonIgnore;
 import com.fasterxml.jackson.annotation.JsonInclude;
+import org.apache.commons.io.FilenameUtils;
```
Comment (apigatewayopensource) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Policy.java]: Code Smell Code Smell: Remove this unused import 'org.apache.commons.io.FilenameUtils'. ([squid:UselessImportCheck](https://sonarcloud.io/organizations/ca-api-gateway/rules#rule_key=squid%3AUselessImportCheck))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=com.ca.apim.gateway%3Agateway-developer-plugin&pullRequest=135&issues=AWcuGG63kEeD8QRk-1yR&open=AWcuGG63kEeD8QRk-1yR)

[ISSUE_KEY]: AWcuGG63kEeD8QRk-1yR

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Folder.java [hunk 3]
```diff
@@ -32,4 +38,8 @@ public void setPath(String path) {
         this.path = path;
     }
 
+    @Override
```
[the remark this answers is not in the document]
Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/beans/Folder.java]: I am not sure if path is an attribute of Folderable, I understand your point, I don't like that much repeated code too, I will think some time about it =)

The postload params are used in other places, I don't know if we can do many things here

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/FolderLoaderUtils.java [hunk 4]
```diff
@@ -82,9 +84,9 @@ static void createFoldersAlongPath(final String stringPath, Map<String, Folder>
         for (final Path p : paths) {
             Folder parentFolder = p.getParent() == null ?
                     rootFolder :
-                    folderMap.get(p.getParent().toString() + "/");
+                    folderMap.get(separatorsToUnix(p.getParent().toString()) + "/");
```
[the remark this answers is not in the document]
Comment (joao-borges) [reply config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/config/loader/FolderLoaderUtils.java]: File.separator on windows is `\` and will break the whole purpose here
The idea is all auto-generated paths have the unix separator `/` and the whole plugin use only that. So hardcoding here is not that bad.

I will create a PathUtils class to encapsulate all this separator replacements and get the same for everything.

File: config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/paths/PathUtils.java [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+ * Utility class to handle operations related to path names and separators.
+ */
+public class PathUtils {
+
+    // Constant to be used for the path separation, forcing to be the unix separator.
+    public static final String PATH_SEPARATOR = "/";
+
+    private PathUtils() {}
+
+    public static String path(@NotNull String first, String... more) {
```
Comment (yves-chan) [inline config-builder/src/main/java/com/ca/apim/gateway/cagatewayconfig/util/paths/PathUtils.java]: Should we add 'unix' in front of these methods so that it is more specific?
